services:
  test:
    build: .
    ports:
      - "6969:6969"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]

    volumes:
    - /home/varoo/Models/:/models/
